### ISSUE TITLE
Data types for decimal128 are not matching in model and document

### ISSUE THREAD

**Issue by kawfong** [francescov1/mongoose-tsgen#105]
Type-gen for Decimal128 in `User` is number 
https://github.com/francescov1/mongoose-tsgen/blob/0bd325755401fbcc4b48e994b79a2dca8a111cfd/src/helpers/tests/artifacts/user.gen.ts#L73

but it's mongoose.Types.Decimal128 in `UserDocument`
https://github.com/francescov1/mongoose-tsgen/blob/0bd325755401fbcc4b48e994b79a2dca8a111cfd/src/helpers/tests/artifacts/user.gen.ts#L202

Is this expected? How do we reserve decimal128 when we want to use the `Model`?

**Comment by francescov1** [comment]
Hi @kawfong, `Number` seemed like the best choice that Typescript had to offer to represent `Decimal128`. If Typescript has a more accurate type that we can use, I am happy to change it.

**Comment by kawfong** [comment]
Why don't we keep it as `mongoose.Types.Decimal128`? I'm still relatively new to Typescript, I'm not sure what's the best practice here. It seems odd to me that the data types for fields in `User` are not matching with the data types in `UserDocument`

**Comment by francescov1** [comment]
@kawfong Every Mongoose model has 2 Typescript types generated, in this case `User` and `UserDocument`. The purpose of `User` is to have a Typescript type which does not have any dependency on Mongoose. This is especially useful for usage in frontends, or any other environment where we don't want to have Mongoose as a dependency. 

For general usage of Mongoose documents, you can always use `UserDocument`, there is no need to use `User`.

**Comment by kawfong** [comment]
That makes sense. I'm not sure if string would be a better representation of `Decimal128`. Coz number basically defeats the purpose of using `Decimal128`. 

Let's say someone is using `User` to store `$1.99` dollar in `number `and it gets translated to `$1.99` in `Decimal128`. And this is fine. When someone retrieve it again, it might not be `$1.99` as `number` in `User` anymore. In terms of reserving precisions, I think `string` could be a better representation. However, that kinda forces the caller to convert `string` to some other data types if they ever need to do any operations.

**Comment by kawfong** [comment]
Got it. Thank you very much for the explanation. 

I'm wondering what's going to happen if someone trying to do operations on the `number` but it's `decimal128` under the hood. Just an incorrect value instead of a runtime error? I'm not sure whether `string` is better than `number` or vice versa anymore.

I'll close the comment for now. Thank you for your great work! mongoose-tsgen definitely improves our dev life a lot!

**Comment by francescov1** [comment]
I'm not too sure, I haven't worked closely with `Decimal128`. If you find out more info about it and find it warrants a change here I'm happy to consider it.

Thanks!
