### ISSUE TITLE
"SyntaxError: Cannot use import statement outside a module" error in Sveltekit apps

### ISSUE THREAD

**Issue by JoschiGrey** [francescov1/mongoose-tsgen#109]
Hey,

if you try to run this in a sveltekit application you get the error "SyntaxError: Cannot use import statement outside a module".

To reproduce it:
```
npm create svelte@latest my-app
cd my-app
npm install
npm install mongoose
npm install mongoose-tsgen
```
Create src/models/test.ts
```ts
import mongoose, { Schema } from "mongoose";

const customSchema = new Schema({
    name: String
})

export const MyModel = mongoose.model("Custom", customSchema)
```
run `npx mtgen`

The default package.json already sets `"type":"module"`

**Comment by francescov1** [comment]
Hi @JoschiGrey ,

This is not a problem with mongoose-tsgen, rather with your environment which is not allowing for import statements. I dont have any experience with sveltekit so I dont think I can help much, sorry about that!

Closing this off, but feel free to re-open if you think necessary.
