### ISSUE TITLE
Update @ts-morph/common?

### ISSUE THREAD

**Issue by Narretz** [francescov1/mongoose-tsgen#116]
ts-morph/common is already at typescript 5, which is significantly smaller than typescript 4 and should probably not work any differently for the purpose it's used here. Can it be updated?

**Comment by francescov1** [comment]
Should be fine, do you want to test this PR to verify that the build is slimmer as expected? https://github.com/francescov1/mongoose-tsgen/pull/117

**Comment by francescov1** [comment]
Live in v9.2.5!
