### ISSUE TITLE
"default" ignored

### ISSUE THREAD

**Issue by adrianwiechec-at-optilyz** [francescov1/mongoose-tsgen#127]
The `default` field in schema spec seems to be ignored. For example, for the following user model:
```// user.js
import { Schema, model } from "mongoose";

const UserSchema = new Schema({
  firstName: {
    type: String,
    default: "George",
  },
});

export const User = model("User", UserSchema);
```
after running `npx mtgen user.js`, I get:
```
export type User = {
  firstName?: string;
  _id: mongoose.Types.ObjectId;
};
```
with `firstName` as optional field, while clearly it will never actually be undefined, so I'm expecting just:
```
export type User = {
  firstName: string;
  _id: mongoose.Types.ObjectId;
};
```

**Comment by francescov1** [comment]
Hi @adrianwiechec-at-optilyz, thanks for pointing this out.

I'll look at fixing this ASAP. As a workaround, you can provide `required: true`.

**Comment by francescov1** [comment]
@adrianwiechec-at-optilyz after reviewing, the current behaviour is actually correct.

If you do not specify `required: true` on a field, it is not a required parameter, even if it has a default value. In this case, it is an optional field which gets initialized to a default value, but can be unset at a later point in time.

**Comment by adrianwiechec-at-optilyz** [comment]
That's a bummer (on Mongoose side), but thanks for looking into this! :bow:
