### ISSUE TITLE
Types for custom statics

### ISSUE THREAD

**Issue by akshay-nm** [francescov1/mongoose-tsgen#141]
We have a plugin for soft deletes through which we add some utils on each schema. 
The types show up with any when generated using mtgen. 

thoughts?

**Comment by francescov1** [comment]
Can you share an example? And link the library you're using.

Would probably need some custom logic to handle typing the extra utils, since mtgen only looks for the expected fields from mongoose schemas. If its a popular library or if the fix is simple enough to add Im happy to add it.

**Comment by akshay-nm** [comment]
It's something built inhouse.
No longer required by my team I guess...
