### ISSUE TITLE
Option to replace Date with string (like --no-mongoose replaces ObjectId with string)

### ISSUE THREAD

**Issue by akshay-nm** [francescov1/mongoose-tsgen#149]
I am using -no-mongoose flag to generate types used in frontend.
But my query responses have dates as string.
For example, 
```
type User {
  createdAt: Date
}
```
But what I get from query response is 
```
type User {
  createdAt: string
}
```
it'd be nice to have another flag, or some way to configure this.

**Comment by francescov1** [comment]
Sorry for the delay @akshay-nm, great suggestion. Just added this feature in v9.3.3 with flag `--dates-as-strings` 🚀
