### ISSUE TITLE
Imports are failing

### ISSUE THREAD

**Issue by jimzhang93** [francescov1/mongoose-tsgen#31]
For imports that use a custom prefix in the `tsconfig.json`, the generator is failing when encountering these. For example:

![image](https://user-images.githubusercontent.com/5386973/106654038-96245d80-6565-11eb-9d36-97d35c4246aa.png)

**Comment by www-chique** [comment]
sdasdds

**Comment by francescov1** [comment]
Nice catch, will update when fixed!

**Comment by francescov1** [comment]
Do you mind providing an example of your tsconfig & any other relevant snippets?

**Comment by francescov1** [comment]
Checking in if this is still an issue, if so do you mind providing an example?
