### ISSUE TITLE
Ignore a file in the directory

### ISSUE THREAD

**Issue by shahidcodes** [francescov1/mongoose-tsgen#50]
How can I ignore a file in the models folder.  I've some imports in models/index.ts which is causing a generation to fail.

**Comment by francescov1** [comment]
What does your folder structure look like and how are you running the generator? There is not currently an explicit option to ignore certain paths (although its in the roadmap) but there are other ways you can achieve this, just need to better understand your use case.

**Comment by shahidcodes** [comment]
I was able to solve the problem using -i (--import) and changing the import from
```
import Bootstrap from '@/backend/bootstrap'
```

To 

```
import Bootstrap from '../../backend/bootstrap'
```

Also my folder structure is like below
```
/models
    /index.ts - re exports all the models in the folder, with some login to connect to dB 
    /user.ts - model file
```

**Comment by francescov1** [comment]
Awesome, great to hear!
