### ISSUE TITLE
run mtgen got error: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by aaronyu6** [francescov1/mongoose-tsgen#76]
## tsgen error     RangeError: Maximum call stack size exceeded

environment: mongoose 5.13.10

```
 npx mtgen src/survey/schema/candidateStat.schema.ts -o src/survey/interface/candidateStat.ts
Generating mongoose typescript definitions... !
    RangeError: Maximum call stack size exceeded
```

Solution: mongoose must run with version 6, version 5.x.x cause the above error. don't know why

**Comment by francescov1** [comment]
Hey @aaronyu6, can you provide an example of the schema in question? Thanks!

**Comment by francescov1** [comment]
Hi @aaronyu6 ,

Im not able to reproduce this. Can you provide a simple repo to repro? Thanks

**Comment by francescov1** [comment]
Havent seen this occur with any other users and unable to repro, going to close off for now. Feel free to re-open if its still occurring.

**Comment by iserdmi** [comment]
@francescov1 Hello. If you set any attribute of your model to: { type: 'Boolean', default: false } script will throw Maximum call stack size exceeded on parseSchema fn here:
```
    Object.keys(schemaTree).forEach((key) => {
        const val = schemaTree[key];
        template += parseKey(key, val);
```

**Comment by francescov1** [comment]
@iserdmi Will put up a fix shortly. As a workaround, you can use `{ type: Boolean, default: false }` (notice that `Boolean` is not a string, but the global object). Mongoose has many ways to define these types so thanks for pointing this out 🙏

**Comment by francescov1** [comment]
https://github.com/francescov1/mongoose-tsgen/pull/97

**Comment by francescov1** [comment]
@iserdmi Fix is live in `9.0.6` 🚀

**Comment by iserdmi** [comment]
@francescov1 Thank you very much for this fix!

But now I faced with another problem. Looks like that they are related to each other.

I have model:

```
const courseLessonSchema = new Schema({
  alias: { type: 'String', required: true },
  title: { type: 'String', required: true },
  desc: { type: 'String' },
  free: { type: 'Boolean', default: false, required: true },
  ready: { type: 'Boolean', default: false, required: true },
  becomeReadyAt: { type: 'Date' },
  creatingDuration: { type: 'Number', default: 7, required: true },
  videoUrl: { type: 'String' },
  content: { type: 'String' },
  index: { type: 'Number', required: true },
  autoFinish: { type: 'Boolean', default: false, required: true },
})
```

Generator works fine and generate this:
```
/**
 * Mongoose Schema type
 *
 * Assign this type to new CourseLesson schema instances:
 * ```
 * const CourseLessonSchema: CourseLessonSchema = new mongoose.Schema({ ... })
 * ```
 */
export type CourseLessonSchema = mongoose.Schema<
  CourseLessonDocument,
  CourseLessonModel,
  CourseLessonMethods,
  CourseLessonQueries
>
```

Then I apply it to my schema:
```
const courseLessonSchema: CourseLessonSchema = new Schema({
  alias: { type: 'String', required: true },
  ...
})

And now whole object inside new Schema() marked as red with message: "Type instantiation is excessively deep and possibly infinite"

I get this error in all my other schemas. 

My mongoose version: 6.3.5

Can you please help me, to figure out?

I am trying to move my project form js to ts. I am already tried typegoose (don't like it). I am already tried to make types for my models by my self (don't like it). I think mongoose-tsgen — the best approach, but I need some help to implement it 🙂

**Comment by francescov1** [comment]
I believe this issue is due to an incompatibility with a new Mongoose Typescript change, see [here](https://github.com/Automattic/mongoose/issues/11787) for more details.

We likely wont be addressing this problem, since the next major version of Mongoose contains type inference and will make this package obsolete. In the meantime, you can use `--no-populate-overload` to get around this.

**Comment by iserdmi** [comment]
@francescov1 Thanks for recomendation! Tell me please, where I can read more about «next major version of Mongoose contains type inference»?

**Comment by francescov1** [comment]
@iserdmi Here is the PR https://github.com/Automattic/mongoose/pull/11563.

It looks like I will be continuing support for mongoose-tsgen since there's quite a few use cases in which it is still useful. See the comments at the end of that PR for more details
