### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 424

### ISSUE THREAD

**Issue by subhamg** [francescov1/mongoose-tsgen#81]
Hi!
Please help me to fix this issue. I tried validating JSON and I'm still getting this issue. 

![vscode](https://user-images.githubusercontent.com/60707860/152140130-0ed65bd7-a71b-4032-bb9e-9ac99bdaeeea.jpg)
![Terminal](https://user-images.githubusercontent.com/60707860/152140156-7e593d9d-fa18-49f8-93ae-fd3b47a59959.jpg)

**Comment by francescov1** [comment]
Hi @subhamg ,

It looks like you are running `mtgen` on a file called `user_model.ts`, but the file shown above is `user.ts`. Do you mind providing an example of `user_model.ts`?

**Comment by subhamg** [comment]
> Hi @subhamg ,
> 
> It looks like you are running `mtgen` on a file called `user_model.ts`, but the file shown above is `user.ts`. Do you mind providing an example of `user_model.ts`?
> 
> I think you should be running `npx mtgen src/models/user.ts` to target the Mongoose schema you provided above.

Hi @francescov1 
You can see the last two lines on my terminal image. I have run the command `npx mtgen src/models/user.ts`  for the `user.ts` file and got the same error.

**Comment by francescov1** [comment]
Hmm this looks like a potential issue with your schema or project. If you can provide a simple repo to reproduce this I can investigate further, but doesn't seem like an issue with mtgen

**Comment by gadielkalleb** [comment]
I got the same error, got here in this issue.
but I started to debug locally, I made a new project using the examples here in the repository as a basis.

and got the same errors

I made some adjustments to the already transpiled code, and it works again.

in the print we see on the left where I moved, on the right another that I used directly after installing this lib.

there is something wrong in this source code in the return of reading the files that are JSON.

where it returned JSON.parse I changed it to return the object/json itself.

but you will need to make this change in the source directly.

![image](https://user-images.githubusercontent.com/25777532/153959938-d8a794da-3fc5-4ccf-8069-f10e290dd247.png)

**Comment by gadielkalleb** [comment]
hi @subhamg, did you manage to solve this problem?

**Comment by francescov1** [comment]
@subhamg Deployed a fix in version 9.0.1 with the help of @gadielkalleb. The issue wasn't very deterministic, so feel free to re-open this if you are still seeing this error

**Comment by dimaip** [comment]
In my case, I have had a trailing comma in my `tsconfig.json`...
Some better error message like `Failed parsing your tsconfig.json file` could have saved me a few minutes.
